from pathlib import Path

LATEST_VERSION_STR = "latest"

CONFIG_FILE_PATH = Path().home() / ".multinode" / "config.json"
DEFAULT_API_URL = "https://control.quantumboost-development.com"

PROJECT_NAME_ENV = "MULTINODE_PROJECT_NAME"
VERSION_ID_ENV = "MULTINODE_VERSION_ID"
FUNCTION_NAME_ENV = "MULTINODE_FUNCTION_NAME"
INVOCATION_ID_ENV = "MULTINODE_INVOCATION_ID"
EXECUTION_ID_ENV = "MULTINODE_EXECUTION_ID"
CONTROL_PLANE_API_URL_ENV = "MULTINODE_API_URL"
CONTROL_PLANE_API_KEY_ENV = "MULTINODE_PLANE_API_KEY"

ROOT_WORKER_DIR = "/app"
