from typing import Optional

from control_plane.types.datatypes import VersionId, ExecutionLogs


class LogsApiHandler:
    """
    API method for getting logs generated by an execution.
    """

    def get_execution_logs(
        self,
        project_name: str,
        version_id: VersionId,
        function_name: str,
        invocation_id: str,
        execution_id: str,
        max_lines: int = 50,
        cursor: Optional[str] = None,
    ) -> ExecutionLogs:
        """
        :raises ProjectDoesNotExist:
        :raises VersionDoesNotExist:
        :raises FunctionDoesNotExist:
        :raises InvocationDoesNotExist:
        :raises ExecutionDoesNotExist:
        """
        raise NotImplementedError
