# Environment variables injected by the control plane into the workers
PROJECT_NAME_ENV = "MULTINODE_PROJECT_NAME"
VERSION_ID_ENV = "MULTINODE_VERSION_ID"
FUNCTION_NAME_ENV = "MULTINODE_FUNCTION_NAME"
INVOCATION_ID_ENV = "MULTINODE_INVOCATION_ID"
EXECUTION_ID_ENV = "MULTINODE_EXECUTION_ID"
CONTROL_PLANE_API_URL_ENV = "MULTINODE_API_URL"
CONTROL_PLANE_API_KEY_ENV = "MULTINODE_API_KEY"
