# Environment variables injected by the control plane into the workers
PROJECT_NAME_ENV = "PROJECT_NAME"
VERSION_ID_ENV = "VERSION_ID"
FUNCTION_NAME_ENV = "FUNCTION_NAME"
INVOCATION_ID_ENV = "INVOCATION_ID"
EXECUTION_ID_ENV = "EXECUTION_ID"
CONTROL_PLANE_API_URL_ENV = "CONTROL_PLANE_API_URL"
CONTROL_PLANE_API_KEY_ENV = "CONTROL_PLANE_API_KEY"
